/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(auth)/login': RouteRecordInfo<
      '/(auth)/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/register': RouteRecordInfo<
      '/(auth)/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(root)/': RouteRecordInfo<
      '/(root)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(root)/[...path]': RouteRecordInfo<
      '/(root)/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/(root)/about': RouteRecordInfo<
      '/(root)/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(root)/contact': RouteRecordInfo<
      '/(root)/contact',
      '/contact',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/app/(auth)/login.vue': {
      routes:
        | '/(auth)/login'
      views:
        | never
    }
    'src/app/(auth)/register.vue': {
      routes:
        | '/(auth)/register'
      views:
        | never
    }
    'src/app/(root)/index.vue': {
      routes:
        | '/(root)/'
      views:
        | never
    }
    'src/app/(root)/[...path].vue': {
      routes:
        | '/(root)/[...path]'
      views:
        | never
    }
    'src/app/(root)/about.vue': {
      routes:
        | '/(root)/about'
      views:
        | never
    }
    'src/app/(root)/contact.vue': {
      routes:
        | '/(root)/contact'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
