import React from 'react';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';

import ThemeProvider from '@/providers/ThemeProvider';

const fontSans = FontSans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fontSans.className}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
